MovieECommerce/Controllers/ActorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MovieECommerce.Contract;
using MovieECommerce.Models;
using MovieECommerce.ViewModels;

namespace MovieECommerce.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorRepository _actorRepo;
        private readonly IImageService _imageService;
        private readonly IMapper _mapper;

        public ActorController(IActorRepository actorRepo, 
                               IImageService imageService,
                               IMapper mapper)
        {
            _actorRepo = actorRepo;
            _imageService = imageService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _actorRepo.GetAllActorsAsync();
            return View(data);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ActorViewModel model)
        {
            if (!ModelState.IsValid)
            {
               return View(model);
            }

            var actor = _mapper.Map<Actor>(model);

            //Add Actor photo to Cloudinary and generate absolute path
            string imgUrl = "";

            if (model.ProfilePictureURL is not null)
            {
                var filePath = Path.GetTempFileName();

                using (var stream = System.IO.File.Create(filePath))
                {
                    await model.ProfilePictureURL.CopyToAsync(stream);
                }
                var uploadResult = await _imageService.UploadImage(filePath);
                imgUrl = uploadResult;
            }

            actor.ProfilePictureURL = imgUrl;
            var result = await _actorRepo.AddActorAsync(actor);
            if (result)
            {
                TempData["ActorAddedSuccessfully"] = "Actor successfully added.";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Actor could not be added";
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string actorId)
        {
            var actor = await _actorRepo.GetActorAsync(a => a.ActorId == actorId);
            if(actor == null)
            {
                TempData["ActorNotFound"] = "Actor could not be found.";
                return RedirectToAction("Index");
            }

            //Map the Actor to ActorEditViewModel since the Edit view takes ActorEditViewModel
            var editActor = _mapper.Map<ActorEditViewModel>(actor);
            return View(editActor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ActorEditViewModel model)
        {
            var actorToModify = await _actorRepo.GetActorAsync(a => a.ActorId == model.ActorId);
            if (actorToModify == null)
            {
                TempData["Error"] = "Could not update Actor";
                return View(model);
            }

            if(model.NewProfilePictureURL != null && model.NewProfilePictureURL.Length > 0)
            {
                var filePath = Path.GetTempFileName();
                 
                using (var stream = System.IO.File.Create(filePath))
                {
                    await model.NewProfilePictureURL.CopyToAsync(stream);
                }
                var imageUplaodURL = await _imageService.UploadImage(filePath);

                if(imageUplaodURL == null)
                {
                    TempData["Error"] = "Could not update Actor";
                    return View(model);
                }

                //Assign NewProfilePictureURL to profilePictureURL of original actor
                actorToModify.ProfilePictureURL = imageUplaodURL;
            }

            actorToModify.FullName      = model.FullName;
            actorToModify.BioInformation = model.BioInformation;

            var result = await _actorRepo.UpdateActorAsync(actorToModify);
            if (result)
            {
                TempData["Success"] = "Actor Successfully Modified";
                return RedirectToAction("Detail", new { actorId = actorToModify.ActorId });
            }
            return View();
        }


        public async Task<IActionResult> Detail(string actorId)
        {
            var actor = await _actorRepo.GetActorAsync(a => a.ActorId == actorId);
            var actorDetail = _mapper.Map<ActorEditViewModel>(actor);
            return View(actorDetail);
        }
    }
}

MovieECommerce/Controllers/CinemaController.cs
using Microsoft.AspNetCore.Mvc;
using MovieECommerce.Contract;

namespace MovieECommerce.Controllers
{
    public class CinemaController : Controller
    {
        private readonly ICinemaRepository _cinemaRepo;

        public CinemaController(ICinemaRepository cinemaRepo)
        {
            _cinemaRepo = cinemaRepo;
        }
        public async Task<IActionResult> Index()
        {
            var cinemas = await _cinemaRepo.GetCinemas();
            return View(cinemas);
        }
    }
}

MovieECommerce/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MovieECommerce.Contract;

namespace MovieECommerce.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepo;

        public MovieController(IMovieRepository movieRepo)
        {
            _movieRepo = movieRepo;
        }
        public async Task<IActionResult> Index()
        {
            var movies = await _movieRepo.GetMovies();
            return View(movies);
        }

        [HttpPost]
        public IActionResult Search()
        {
            return View();
        }
    }
}

MovieECommerce/Controllers/ProducerController.cs
 using Microsoft.AspNetCore.Mvc;
using MovieECommerce.Contract;

namespace MovieECommerce.Controllers
{
    public class ProducerController : Controller
    {
        private readonly IProducerRepository _producerRepo;

        public ProducerController(IProducerRepository producerRepo)
        {
            _producerRepo = producerRepo;
        }
        public async Task<IActionResult> Index()
        {
            var producers = await _producerRepo.GetProducersAsync();
            return View(producers);
        }


    }
}

MovieECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieECommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movie" asp-action="Index">MovieECommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Movie"><i class="badge-info bi-film"></i>Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                            <div class="drpdown">
                                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="navBarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </button>

                                <div class="dropdown-menu" aria-labelledby="navBarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i> Producer</a>
                                    <a class="dropdown-item" asp-controller="Actor" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </div>
                        </li>
                    </ul>


                    <form class="d-flex form-inline my-2 my-lg-0" style="padding-right: 10px;" method="post" asp-controller="Movie" asp-action="Search">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a Movie..." />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieECommerce
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>